#Import items needed - to open HTML file after being run and some operating system requirements

import webbrowser
import os

#Opens ISBN.txt file to be read
isbnFile = open("isbn.txt","r")

#Creates the var isbnList for adding ISBN numbers into
isbnList = list()

#Creates a for loop to add the ISBN numbers in the lsit 
for line in isbnFile:
    isbnList.append(line.strip())

#Crates a Variable with the number of items in the list
isbnListLength = len(isbnList)
        
#Creates a HTML file called isbn_reader.html and uses the content manager
with open("isbn_reader.html", "w") as isbnHtml:
    #Uses the .writelines command to create the HTML code
    #Also includes CSS for styles of webpage
    #Includes link to font from Google
    isbnHtml.writelines("""
        <!DOCTYPE html>
            <head>
            <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
            <style>
            body {
                background-color: #080808;
                text-align:center;
                font-family: 'Roboto', sans-serif;
            }
            
            h1 {
                color: #E0DAD8
            }
            
            h2 {
                color: #E0DAD8
            }
            
            a:link {
                color: #8C18AE
            }
            
            a:visited {
                color: #8C18AE
            }
            
            a:hover {
                color: #E0DAD8
            }
            
            a:active {
                color: #8C18AE
            }
            
            </style>
            <title>Project Two - ISBN Reader</title>
            <h1>Webpage generated by ISBN list in Python</h1><br>
            <h2>Created by Scott Adams</h2><br>
            </head>
            <body>""")
    
    #Uses the ISBN numbers stored in the list to put image into HTML file
    for isbnLoop in isbnList:
            #Adds the image for each ISBN value
            isbnHtml.write(" <img src=\"http://covers.openlibrary.org/b/isbn/" + isbnLoop +"-L.jpg\" />")
            #Creates a line break
            isbnHtml.write("<br>")
            #Adds the link to click on to goto more information about the book
            isbnHtml.write(" <p><a href=\"http://openlibrary.org/isbn/" + isbnLoop +"\" target=\"_blank\">More information on " + isbnLoop + "</a></p>")
            isbnHtml.write("<br>")
    
    #Uses the .writelines command to create the HTML code         
    isbnHtml.writelines("""   
            </body>
        </html>""")

     
    #Opens up the Webapge isbn_reader.html page
    webbrowser.open("file://" + os.path.realpath("isbn_reader.html")) 
    
    #closes the isbnFile
    isbnFile.close()
    